# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: salesforce/salesforcedx:7.209.6-full


definitions:
  steps:
    - step: &installPlugin
        name: Install Plugin
        script:
          - echo "Install Plugin goes here..."
          - echo y | sfdx plugins:install sfpowerkit
          - node -v
          - git --version
          - sfdx --version
          - sfdx plugins
          
    - step: &generateDelta
        name: Generate Delta
        script:
          - echo "Generate Delta goes here..."
          - echo y | sfdx sfpowerkit:project:diff --revisionfrom fb3d20c7151 --revisionto HEAD --output deltaChanges --apiversion 57.0 -x
          
    - step: &buildConvert
        name: Build and Convert
        script:
          - echo "Build Convert goes here..."
          - sfdx project:convert:source -r ./deltaChanges -d ./deltaChangesDeploy
         
    - step: &deployWithoutTests
        name: Deploy Without Tests
        script:
          - echo "Deploy Without Tests goes here..."
    
    - step: &deployWithTests
        name: Deploy WithTests
        script:
          - echo "Deploy With Tests goes here..."
          
    - step: &validateWithoutTests
        name: Validate Without Tests
        script:
          - echo "Validate Without Tests goes here..."
    
    - step: &validateWithTests
        name: Validate WithTests
        script:
          - echo "Validate With Tests goes here..."
          
pipelines:
  custom: # Pipelines that can only be triggered manually
    'ValidateCICD':
      - step: *installPlugin
      - step: *generateDelta
      - step: *buildConvert
      - step: 
          <<: *validateWithoutTests
          deployment: cicd